version: "3.9"

networks:
  lab_network:
    driver: bridge

volumes:
  pgdata:
    driver: local

services:
  server:
    image: nginx:latest
    container_name: nginx
    networks:
      - lab_network
    build:
      context: .
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  rabbitmq:
    image: rabbitmq:3.13.0-rc.2-management-alpine
    container_name: rabbitmq
    networks:
      - lab_network
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  service1:
    container_name: service1
    build:
      context: .
      dockerfile: service1/Dockerfile
    ports:
      - "8000:80"
    networks:
          - lab_network
    depends_on:
      - db

  service2:
    container_name: service2
    build:
      context: .
      dockerfile: service2/Dockerfile
    networks:
      - lab_network
    ports:
      - "8001:80"
    depends_on:
      - db

  sender:
    container_name: sender
    networks:
      - lab_network
    build:
      context: .
      dockerfile: sender/Dockerfile
    depends_on:
      - rabbitmq
      - db

  consumer:
    container_name: consumer
    networks:
      - lab_network
    build:
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      - rabbitmq
      - db
  db:
    networks:
      - lab_network
    image: postgres:14.1-alpine
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: laba
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
